services:
  minibot:
    image: minibot
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ENV_PATH=/run/secrets/minibot-tokens
    secrets:
      - minibot-tokens

secrets:
  minibot-tokens:
    file: ./secrets.env