name: Docker Image Push

# This workflow runs when any of the following occur:
# - A push is made to a branch called `master`
# - A tag starting with "v" is created
# - A pull request is created or updated to master
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
env:
  IMAGE_NAME: minibot

jobs:
  # This pushes the image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]') # upper to lower
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,') # strip git ref prefix from version
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//') # strip "v" prefix from tag name
          [ "$VERSION" == "master" ] && VERSION=latest # use docker `latest` tag convention
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
